---
title: "Plotting conidia count data"
author: "Kelly Carscadden"
date: '2020-03-29'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Simulating data to illustrate a specific line graph construction for a friend. Example data is conidia counts from different plate replicates at different dilutions over time.

```{r}
library(tidyverse)
```

```{r}
#imagining 3 different sample IDs, 
#3 plate reps of each dilution
#3 dilutions
#2 different time points, and the sample IDs start at different times

conidia <- data.frame(prep_ID = rep(letters[1:3], each = 18),
           day_from_1 = rep(c(1,14,35,42,44,46), each = 9),
           dilution = as.factor(rep(rep(c(1,2,3), each=3), 6)),
           plate_rep = rep(c(1,2,3), 18),
           counts = rnorm(18, mean = 50, sd = 8)
)
#made a dilution a factor so it could modify plotting point shape

head(conidia, n=12)         
```

Playing with the data to make it more like the format my friend is collecting from her experiment.

```{r}
#changing this to the format closer to how the data is being collected
conidia_wide <- conidia %>% pivot_wider(names_from = dilution, values_from = counts)

#NOTE - she would read the actual experimental data in here
#conidia_wide <- read_csv("file_name.csv")

#showing how to get to the format for the ggplot code below
#ie collapsing dilution into one column, elongating dataframe
conidia_long <- conidia_wide %>% pivot_longer(cols=c(`1`, `2`, `3`), names_to = "dilution", values_to = "counts")

```

Creating a line graph to show counts over time, per prep_ID, averaged across plate_rep

```{r}
#add some jitter to ensure points don't overlap
pd <- position_dodge(1.5)

#calculate mean, sd and then plot
conidia_long %>%
  group_by(prep_ID, dilution, day_from_1) %>%
  summarise(mean = mean(counts),
            sd = sd(counts)) %>%
  ggplot(aes(x = day_from_1, y = mean, 
             col = prep_ID, pch = dilution))+
  geom_errorbar(aes(ymin = mean-sd, ymax = mean + sd), 
                width=.1, position = pd)+
  geom_point(position = pd)+
  geom_line(position = pd, aes(group = interaction (prep_ID, dilution)))+
  labs(x="Day", y="Mean conidia count")
```
